const mockDataAutoCompleteresponse = [
  {
    Version: 1,
    Key: "993994",
    Type: "City",
    Rank: 85,
    LocalizedName: "Sdier",
    Country: { ID: "DE", LocalizedName: "Germany" },
    AdministrativeArea: { ID: "SN", LocalizedName: "Saxony" },
  },
  {
    Version: 1,
    Key: "3334835",
    Type: "City",
    Rank: 85,
    LocalizedName: "Sdad-Dkhar",
    Country: { ID: "IN", LocalizedName: "India" },
    AdministrativeArea: { ID: "ML", LocalizedName: "Meghalaya" },
  },
  {
    Version: 1,
    Key: "3338317",
    Type: "City",
    Rank: 85,
    LocalizedName: "Sder",
    Country: { ID: "IN", LocalizedName: "India" },
    AdministrativeArea: { ID: "ML", LocalizedName: "Meghalaya" },
  },
  {
    Version: 1,
    Key: "3333559",
    Type: "City",
    Rank: 85,
    LocalizedName: "Sdhnongkalong",
    Country: { ID: "IN", LocalizedName: "India" },
    AdministrativeArea: { ID: "ML", LocalizedName: "Meghalaya" },
  },
  {
    Version: 1,
    Key: "2545610",
    Type: "City",
    Rank: 85,
    LocalizedName: "Sdruzzina'",
    Country: { ID: "IT", LocalizedName: "Italy" },
    AdministrativeArea: { ID: "32", LocalizedName: "Trentino-Alto Adige" },
  },
  {
    Version: 1,
    Key: "2456964",
    Type: "City",
    Rank: 85,
    LocalizedName: "Sdyeslovka",
    Country: { ID: "RU", LocalizedName: "Russia" },
    AdministrativeArea: { ID: "BRY", LocalizedName: "Bryansk" },
  },
  {
    Version: 1,
    Key: "2483506",
    Type: "City",
    Rank: 85,
    LocalizedName: "Sdobnaya Dubrava",
    Country: { ID: "RU", LocalizedName: "Russia" },
    AdministrativeArea: { ID: "ORL", LocalizedName: "Orel" },
  },
];

export default mockDataAutoCompleteresponse;
